<a href="https://colab.research.google.com/github/mr-amit-yadav/Feature_Engineering/blob/main/Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Encoding
1.Nominal/OHE Encoding  <br>
2.Label and Original Encoding<br>
3.Target Guided Odinal Encolding<br>

# Nominal /OHE Encoding
One hot encoding,also known as nominal encoding,is a technique used to present categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit correseponds to a unique category.
For example, if we have a categorical variable "color" with three possible values(red,green,blue), we can represent it as one hot encoding as follows:

1.Red:[1,0,0]<br>
2.Green:[0,1,0]<br>
3.Blue:[0,0,1]<br>

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
## Create a simple dataframe
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
## Create an instance of OneHotEncoder
encoder=OneHotEncoder()

In [ ]:
## Perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [ ]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [ ]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
## for new data
encoder.transform([['blue']]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [ ]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [ ]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Label Encoding
Label Encoding and odinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have categorical variable "color" with three possible values(red,green,blue), we can represent it using label encoding as follows:

1.Red:1<br>
2.Green:2<br>
3.Blue:3<br>

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [ ]:
lbl_encoder.fit_transform(df[['color']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [ ]:
lbl_encoder.transform([['red']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [ ]:
lbl_encoder.transform([['blue']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [ ]:
lbl_encoder.transform([['green']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

### Odinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. For example, if we have a categorical variable "education level" with four possible values (high school, college,graduate), we can represent it using ordinal encoding as follows:<br>
1.High school:1 <br>
2.College:2<br>
3:Graduate:3<br>
4:Post-Graduate:4<br>

In [ ]:
## Odinal Encoding
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [ ]:
# Creating a sample DataFrame with an odinal variable
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
    })

In [ ]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
# Create an instance of Ordinal Encoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [ ]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [ ]:
encoder.transform([['small']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])